FROM python:3.11-slim

WORKDIR /app

# Copy code and requirements
COPY kraken_websocket.py ./
COPY requirements.txt ./

# Install dependencies (Kafka + websocket-client)
RUN pip install --no-cache-dir -r requirements.txt

# Run the producer
CMD ["python", "kraken_websocket.py"]
