FROM python:3.11-slim

WORKDIR /app

# Copy code and requirements
COPY consumer.py ./
COPY requirements.txt ./

# Install dependencies (Kafka)
RUN pip install --no-cache-dir -r requirements.txt

# Run the consumer
CMD ["python", "consumer.py"]
