FROM python:3.11-slim

WORKDIR /app

# Copy the Python script
COPY kafka_topic_viewer.py ./
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "kafka_topic_viewer.py"]
